// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"future-go/go-zero_demo/micro_mall/gate/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GateTestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/get/:id",
				Handler: GetUserHandler(serverCtx),
			},
		},
		// 相应接口添加jwt鉴权
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
