// Code generated by goctl. DO NOT EDIT.
package types

type OrderReply struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	UserName string `json:"userName"`
}

type OrderReq struct {
	Id string `path:"id"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserRegisterReq struct {
	Name   string `json:"name"`
	Gender string `json:"gender"`
}

type UserRegisterRsp struct {
	Id     string `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
}
