version: "3.7"

services:

  # -----------------------------
  # jaeger servcie
  # -----------------------------
  jaeger:
    image: jaegertracing/all-in-one:1.20
    ports:
      - "1314:6831/udp"
      - "1315:16686"
    networks:
      - backend

# -----------------------------
# networks
# -----------------------------
networks:
  backend:
    external: true