// Code generated by goctl. DO NOT EDIT.
package types

type IdRequest struct {
	Id string `path:"id"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserLoginReq struct {
	Username     string `json:"username"`
	Password string `json:"password"`
}

type UserLoginRsp struct {
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Name   string `json:"name"`
	Gender string `json:"gender"`
}

type UserRegisterRsp struct {
	Id      string `json:"id"`
	Name    string `json:"name"`
	Gender  string `json:"gender"`
	Message string `json:"message"`
}

type UserResponse struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	UserName string `json:"userName"`
}
